src/WebRTCLibPeerConnection.cpp
Should check for null before trying to close the peer_connection.
Fixes #7 .
=> Fix crash when closing an invalid peerconnection.

SConstruct, misc/gdnlib.tres
* Fix `osx` platform
* Add `ios` platform
* Fix `GDNativeLibrary` file extension (causing Godot not to recognize it)
* Add missing library entries.
* Link `linux` with '-static-libgcc', '-static-libstdc++' (only 64 bits, 32 bit builds does not like static linking)
=> Add mac and ios platforms. Fix GDNLibrary.

src/WebRTCLibDataChannel.cpp
It's been really long since the plugin has last been updated
=> Fix API breakage after godot cpp 3.2 bump.

SConstruct, src/WebRTCLibDataChannel.hpp, src/WebRTCLibObservers.cpp, src/WebRTCLibPeerConnection.cpp, src/WebRTCLibPeerConnection.hpp, src/init.cpp
WebRTC [`branch-heads/4472`](https://webrtc.googlesource.com/src/+/refs/branch-heads/4472) ([chromium M91](https://chromiumdash.appspot.com/branches)). (commit `92ba70c1c575a82b64ae9c99912c0d2955ee3f15`)
[See here](https://github.com/Faless/webrtc-builds/releases/tag/4472-33644-92ba70c) for pre-compiled static webrtc libraries for all supported platforms, along with instructions on how they were built.
This PR also add a single signalling thread, instead of spawning multiple ones like before.
Hopefully fixing some of the undue crashes.
=> Bump webrtc to branch-heads/4472. Fixes signalling.

.github/actions/webrtc-download/action.yml, .github/workflows/build_release.yml, webrtc/.gitignore, webrtc/linux/.gitignore, webrtc/windows/.gitignore
Includes all supported architectures:
* Android:
- arm (neon)
- arm64
- x86
- x64
* iOS:
- arm
- arm64
- x64 (simulator)
* Linux
- x86
- x64
* macOS
- x64
* windows
- x86
- x64
Use a single matrix for builds, then an extra step will package for release.
Artefacts are generated for each platform/arch combination, along for the 2 zip containing the full `webrtc` and `webrtc_debug` plugin.
Closes #35 (supersedes)
See [here](https://github.com/Faless/webrtc-native/actions/runs/1004558255) for generated artefacts.
=> Setup CI for Android, iOS, Linux, macOS, Windows.

.github/workflows/build_release.yml, SConstruct
Needs a more recent revision of `godot-cpp`, but can still use `godot-headers` from 3.2 . See CI script update for details.
=> Add OSX arm64 build.

src/WebRTCLibDataChannel.cpp, src/WebRTCLibDataChannel.hpp, src/net/WebRTCDataChannelNative.cpp, src/net/WebRTCDataChannelNative.hpp
This is a companion to these PRs:
- Godot 4.x: https://github.com/godotengine/godot/pull/50658
- Godot 3.x: https://github.com/godotengine/godot/pull/50659
This requires a minor change to godot-headers in order to compile:
```
diff --git a/net/godot_webrtc.h b/net/godot_webrtc.h
index 15e2df8..d5260cc 100644
--- a/net/godot_webrtc.h
+++ b/net/godot_webrtc.h
@@ -108,6 +108,13 @@ typedef struct {
void *next; /* For extension? */
} godot_net_webrtc_data_channel;
+/* Extensions to WebRTCDataChannel */
+typedef struct {
+       int (*get_buffered_amount)(const void *);
+
+       void *next; /* For extension? */
+} godot_net_webrtc_data_channel_ext;
+
/* Set the default GDNative library */
godot_error GDAPI godot_net_set_webrtc_library(const godot_net_webrtc_library *);
/* Binds a …
```
=> Add get_buffered_amount() to WebRTCDataChannel (GDNative)

builders.py
Dependencies used to be built with the default option (release for OpenSSL, debug for libdachannel).
They now follow the desired target (producing smaller binaries in release, and bigger in debug).
=> [SCons] Apply "target" to dependencies.

SConstruct, src/init_gdextension.cpp, src/init_gdnative.cpp
Forces ".dll" extension for library when building with mingw.
Override GDN_EXPORT which is incorrectly defined in the upstream gdnative headers (3.x, godotengine/godot#62173) and godot-cpp include (4.0, godotengine/godot-cpp#771) when building for windows with mingw.
Fixes #52
=> [Windows] Fix windows build with mingw.

src/WebRTCLibDataChannel.hpp
It's the engine expected default, and the least surprising for the users since it allows any data to be sent, while text mode requires valid UTF.
See #55
=> Fix default data channel write mode to binary.

tools/cmake.py, tools/openssl.py, tools/rtc.py
The num_jobs (-j flag) was being tracked as part of the cmake and openssl build actions, thus causing a rebuild when compiling with different concurrently.
This commit strip the -j flag from the signature of the actions so scons won't rebuild openssl/libdatachannel when changing the parallelism option.
Fixes a regression introduced in #102 .
=> [SCons] Fix regression causing unnecessary rebuilds.

SConstruct
The "ios_min_version" is missing from godot-cpp-3.x, and the macos CC variable is not explicitely set to "clang".
Since the values are passed to cmake, they used to cause unnecessary rebuilds of libdatchannel when compiling both version 3 and 4.
=> Better normalize the GDNative build environment.

SConstruct
More compatibility at the cost of bigger binaries.
Fixes #110
=> Statically link libgcc and libstdc++ on linux

.github/workflows/build_release.yml, misc/patches/scons_path.diff
So we link to very old glibc and support ancient distros.
Fixes #91
=> Build Linux binaries using the Godot toolchian.

src/WebRTCLibDataChannel.hpp, src/WebRTCLibPeerConnection.hpp
So printing them in Godot shows the proper class name instead of "Wrapped".
=> Add _to_string method to extension classes.

src/WebRTCLibPeerConnection.cpp
Avoid potential crash at exit.
=> Call rtc::Cleanup when unloading the library

SConstruct, misc/dist/linux/symbols-extension.map, misc/dist/linux/symbols-gdnative.map, tools/openssl.py, tools/rtc.py
Since we link with static libstdc++ we need to tell gcc to only export the necessary symbols.
Using "-fvisibility=hidden" will not work, since libstdc++ explicitly export its symbols.
Fixes #127 .
=> [Linux] Only export extension init symbol

src/WebRTCLibPeerConnection.cpp
For now this logs debugging in editor and warning in export. Also wasnt sure what to call to log in godot 3.5, so it only has 4.0.
=> Use Godot primitives for logging, change default log level

SConstruct
You can use it with:
```
scons godot_cpp=/path/to/godot-cpp
```
This commit also forces the new "disable_exceptions" godot cpp option to false since exceptions are needed by libdatachannel, and makes sure to always compile/link with dynamic runtime when using MSVC.
Fixes #126
=> Allow building using a custom godot-cpp verison

.github/workflows/build_release.yml, tools/cmake.py, tools/openssl.py
Update CI to macos-12 (since macos-11 is not longer available.
=> [SCons] Improve CMake and OpenSSL macOS/iOS targets

SConstruct, misc/webrtc.gdextension
Renaming the godot version to "4" resulted in the GDExtension file incorrectly setting "compatibility_minimum = 4" (instead of "4.1")
=> [Build] Fix gdextension file after dropping 4.0

.github/workflows/build_release.yml
Ubuntu 20.04 is no longer supported by GH
=> [CI] Update ubuntu runners to 22.04

SConstruct
=> fix: Add iOS min SDK version link flag
